//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace railwaySwation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int numberOfPassport { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
    }
}
