//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace railwaySwation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainDBEntities1 : DbContext
    {
        public TrainDBEntities1()
            : base("name=TrainDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Passenger> Passengers { get; set; }
        public DbSet<Place> Places { get; set; }
        public DbSet<Train> Trains { get; set; }
        public DbSet<TrainsAndPassenger> TrainsAndPassengers { get; set; }
    }
}
