//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace railwaySwation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public long Id { get; set; }
        public string startTown { get; set; }
        public System.DateTime startDate { get; set; }
        public System.TimeSpan startTime { get; set; }
        public string finishTown { get; set; }
        public System.DateTime finishDate { get; set; }
        public System.TimeSpan finishTime { get; set; }
        public int price { get; set; }
    }
}
